#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
GPU=$(lspci | grep VGA | cut -d ":" -f3 | awk '{print $1}')
graphicstoinstall=$(yad --title="Graphics Drivers" --radiolist --list --no-headers --width=240 --height=233 --button=Cancel:1 --button=Install:0 --column="" --column="" false "ATI" false "Intel" false "nVidia Latest" false "nVidia Legacy" false "nVidia Nouveau")

if [[ "$graphicstoinstall" == *"ATI"* ]]; then
qterminal -e 'sudo /usr/share/VX/graphics-drivers/atigfx'
fi

if [[ "$graphicstoinstall" == *"Intel"* ]]; then
qterminal -e 'sudo /usr/share/VX/graphics-drivers/intelgfx'
fi

if [[ "$graphicstoinstall" == *"Latest"* ]]; then
qterminal -e 'sudo /usr/share/VX/graphics-drivers/nvidia-latest'
fi

if [[ "$graphicstoinstall" == *"Legacy"* ]]; then
qterminal -e 'sudo /usr/share/VX/graphics-drivers/nvidia-legacy'
fi

if [[ "$graphicstoinstall" == *"Nouveau"* ]]; then
qterminal -e 'sudo /usr/share/VX/graphics-drivers/nvidia-nouveau'
fi

exit
