#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
extrastoinstall=$(yad --title="Optional Modules" --checklist --list --no-headers --width=240 --height=269 --button=Cancel:1 --button=Install:0 --column="" --column="" false "Bluetooth" false "Flatpak" false "Pipewire" false "Printing" false "Samba" false "SSH")

cat << EOF > /tmp/mysetup
#!/usr/bin/env bash

EOF
sudo chmod +x /tmp/mysetup

if [[ "$extrastoinstall" == *"Bluetooth"* ]]; then
cat << EOF >> /tmp/mysetup
xbps-install -Syu bluez blueman libspa-bluetooth
usermod -aG bluetooth $_user
echo "$_user added to bluetooth group"
sleep 3
echo ""
EOF
fi

if [[ "$extrastoinstall" == *"Pipewire"* ]]; then
cat << EOF >> /tmp/mysetup
xbps-install -Syu alsa-pipewire pipewire
ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/pipewire.desktop
ln -s /usr/share/applications/pipewire-pulse.desktop /etc/xdg/autostart/pipewire-pulse.desktop
mkdir -p /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d
ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d
sleep 3
echo ""
EOF
fi

if [[ "$extrastoinstall" == *"Printing"* ]]; then
cat << EOF >> /tmp/mysetup
xbps-install -Syu bluez-cups cups cups-filters cups-pk-helper gutenprint foomatic-db gl2ps gtklp ippusbxd system-config-printer-udev
cp /usr/share/applications/cups.desktop /home/$_user/.local/share/applications
echo "Hidden=true" >> /home/$_user/.local/share/applications/cups.desktop
usermod -aG lp,lpadmin $_user
echo "$_user added to lp,lpadmin groups"
sleep 3
echo ""
EOF
fi

if [[ "$extrastoinstall" == *"Samba"* ]]; then
cat << EOF >> /tmp/mysetup
xbps-install -Syu samba
printf "\n" | tee -a /etc/samba/smb.conf
usermod -a -G sambashare $_user
echo "client max protocol = NT1" | tee -a /etc/samba/smb.conf
EOF
fi

if [[ "$extrastoinstall" == *"SSH"* ]]; then
cat << EOF >> /tmp/mysetup
ln -s /etc/sv/sshd /var/service
echo "SSH activated"
sleep 3
echo ""
EOF
fi

cat << EOF >> /tmp/mysetup
echo "Installation complete"
EOF

if [[ -z "$extrastoinstall" ]]; then
	exit
else
	qterminal -e 'sudo /tmp/mysetup'
fi

exit
