#!/usr/bin/env bash

echo "Updating VX files.."
cd /usr/share/VX/github/vx-linux
git config advice.setUpstreamFailure false
git fetch
git checkout -f

echo ""
echo "Installing updated files.."
cp -r etc/* /etc
cp -r usr/* /usr
sleep 3

echo ""
echo "VX update complete"
sleep 5
exit
