#!/bin/bash

key=10975

yad --plug=10975 --tabnum=1 --icons --read-dir=/usr/share/VX/flatpak/audiovideo --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=2 --icons --read-dir=/usr/share/VX/flatpak/development --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=3 --icons --read-dir=/usr/share/VX/flatpak/games --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=4 --icons --read-dir=/usr/share/VX/flatpak/graphics --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=5 --icons --read-dir=/usr/share/VX/flatpak/internet --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=6 --icons --read-dir=/usr/share/VX/flatpak/office --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &
yad --plug=10975 --tabnum=7 --icons --read-dir=/usr/share/VX/flatpak/system --sort-by-name --no-buttons --borders=0 --icon-size=48 --item-width=68 &

yad --notebook --key=10975 --width=780 --height=440 --title="Flatpaks" --no-buttons --tab="Audio &amp; Video" --tab="Development" --tab="Games" --tab="Graphics" --tab="Internet" --tab="Office" --tab="System" --button="Close:0"

