#!/usr/bin/env bash

appimagelauncher=$(mktemp -d)
cd $appimagelauncher

wget https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
rpm2cpio appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm | cpio -idmv
cp -r usr/* /usr

echo ""
echo "Installation complete"
sleep 5
exit
