#!/usr/bin/env bash

bitwardeninstall=$(mktemp -d)
cd $bitwardeninstall
wget "https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=rpm"
rpm2cpio *.rpm | cpio -idmv
cp -r opt usr /

echo ""
echo "Installation complete"
sleep 5
exit
