#!/usr/bin/env bash

braveinstall=$(mktemp -d)
cd $braveinstall

echo "Checking for latest stable release.."
bravelatest=$(curl -s https://api.github.com/repos/brave/brave-browser/releases/latest | grep "browser_download_url.*x86_64.rpm" | cut -d : -f 2,3 | tr -d \")
bravelatestx86_64=$(echo $bravelatest | cut -d ' ' -f1)
wget $bravelatestx86_64
rpm2cpio *.rpm | cpio -idmv
cp -r opt usr /

echo ""
echo "Installation complete"
sleep 5
exit
