#!/usr/bin/env bash

chromeinstall=$(mktemp -d)
cd $chromeinstall

wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
rpm2cpio google-chrome-stable_current_x86_64.rpm | cpio -idmv
cp -r opt usr /

echo ""
echo "Installation complete"
sleep 5
exit
