#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
xbps-install -Syu clamav
usermod -aG _clamav $_user
echo "Added $_user to _clamav group"
sleep 2
echo ""
freshclam
echo ""

cat << EOF > /home/$_user/.local/share/file-manager/actions/scanwithclamav.desktop
[Desktop Entry]
Type=Action
Name=Scan with ClamAV
Icon=clamav
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=all/all;
Exec=qterminal -e 'sudo /usr/share/VX/actions/clam-scan %f'
Name=Default profile
EOF

echo ""
echo "Installation complete"
sleep 5
exit
