#!/usr/bin/env bash

discordinstall=$(mktemp -d)
cd $discordinstall

wget https://dl.discordapp.net/apps/linux/0.0.24/discord-0.0.24.deb
ar x discord-0.0.24.deb
tar -xf data.tar.gz
cp -r usr/* /usr

echo ""
echo "Installation complete"
sleep 5
exit
