#!/usr/bin/env bash

heroicgamesinstall=$(mktemp -d)
cd $heroicgamesinstall

wget https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.5.2/heroic-2.5.2.x86_64.rpm
rpm2cpio heroic-2.5.2.x86_64.rpm | cpio -idmv
cp -r opt usr /

echo ""
echo "Installation complete"
sleep 5
exit
