#!/usr/bin/env bash

internxtinstall=$(mktemp -d)
cd $internxtinstall

wget https://github.com/internxt/drive-desktop/releases/download/v1.9.6/internxt-drive_1.9.6_amd64.deb
ar x internxt-drive_1.9.6_amd64.deb
tar -xf data.tar.xz
cp -r opt/* /opt
cp -r usr/* /usr

echo ""
echo "Installation complete"
sleep 5
exit
