#!/usr/bin/env bash

localinstall=$(mktemp -d)
cd $localinstall

xbps-install -Syu libaio-devel libjpeg-turbo-devel libnuma-devel libxslt-devel ncurses-devel ncurses-libtinfo-devel nss-devel
ln -s /usr/lib/libncursesw.so.6.3 /usr/lib/libncurses.so.5
ln -s /usr/lib/libncursesw.so.6 /usr/lib/libtinfo.so.5

wget https://cdn.localwp.com/releases-stable/6.6.0+6231/local-6.6.0-linux.deb
ar x local-6.6.0-linux.deb
tar -xf data.tar.xz
cp -r opt/* /opt
cp -r usr/* /usr

echo ""
echo "Installation complete"
echo "For LocalWP to work properly your hosts file needs write permission."
sleep 5
exit
