#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
braveinstall=$(mktemp -d)
cd $braveinstall

echo "Checking for latest stable release.."
wget https://github.com/minbrowser/min/releases/download/v1.27.0/min-1.27.0-x86_64.rpm
rpm2cpio min-1.27.0-x86_64.rpm | cpio -idmv
cp -r opt usr /

cp /usr/share/applications/min.desktop /home/$_user/.local/share/applications
sed -i "s#Icon=min#Icon=/usr/share/icons/min.png#g" /home/$_user/.local/share/applications/min.desktop

echo ""
echo "Installation complete"
sleep 5
exit
