#!/usr/bin/env bash

discordinstall=$(mktemp -d)
cd $discordinstall

wget https://downloads.slack-edge.com/releases/linux/4.29.149/prod/x64/slack-4.29.149-0.1.el8.x86_64.rpm
rpm2cpio slack-4.29.149-0.1.el8.x86_64.rpm | cpio -idmv
cp -r usr /

echo ""
echo "Installation complete"
sleep 5
exit
