#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
xbps-install -Syu void-repo-multilib void-repo-nonfree
xbps-install -Syv libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit
xbps-install -Syu mono protontricks steam

echo ""
echo "Installation complete, Steam setup will now continue.."
sleep 5
su -g wheel $_user -c 'steam & exit'
exit
