#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
xbps-install -Syu bridge-utils libvirt qemu virt-manager

ln -s /etc/sv/libvirtd /var/service
ln -s /etc/sv/virtlockd /var/service
ln -s /etc/sv/virtlogd /var/service
usermod -aG libvirt $_user
echo "$_user added to libvirt group"

echo ""
echo "Installation complete"
sleep 5
exit
