#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"
xbps-install -Syu linux6.1-headers virtualbox-ose virtualbox-ose-dkms virtualbox-ose-guest-dkms
virtualboxinstalltmp=$(mktemp -d)
cd $virtualboxinstalltmp

wget https://download.virtualbox.org/virtualbox/7.0.6/Oracle_VM_VirtualBox_Extension_Pack-7.0.6a-155176.vbox-extpack
yes | VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-7.0.6a-155176.vbox-extpack

echo ""
usermod -aG vboxusers $_user
echo "$_user added to vboxusers group"

echo ""
echo "Installation complete"
sleep 5
exit
