#!/usr/bin/env bash

debinstalltmp=$(mktemp -d)
cd $debinstalltmp

ar x $1
echo "Extracting archive.."
tar -xf data.tar.*
find . -maxdepth 1 -type f -delete
cp -r * /
echo ""

echo "Installation complete"
echo ""
sleep 3
exit
