#!/usr/bin/env bash

echo "Setting folder and file permissions.."
find $1 -type d -exec chmod 0755 {} \;
find $1 -type f -exec chmod 0644 {} \;
sleep 1

echo "Folders and files set to 755-644"
sleep 5
exit
