#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"

cd /usr/share/wallpapers
bgimg=$(yad --file --title="Select image for global background" --width=780 --height=440)

if [[ $bgimg == "" ]]; then
	exit
else
	cd /tmp
	convert $bgimg /tmp/background.png
	convert -scale 10% -blur 0x2.5 -resize 1000% $bgimg /tmp/background-blurred.png 
	sudo cp background.png /usr/share/wallpapers
	sudo cp background-blurred.png /boot/grub/themes/vx/background.png
	sudo cp background-blurred.png /usr/share/wallpapers
	pcmanfm-qt --set-wallpaper /usr/share/wallpapers/background.png
	sudo sed -i "s#background=.*#background=/usr/share/wallpapers/background-blurred.png#g" /usr/share/sddm/themes/vx/theme.conf
	sudo sed -i "s#background=.*#background=/usr/share/wallpapers/background-blurred.png#g" /usr/share/sddm/themes/vx/theme.conf.user
	kdialog --msgbox "Background changed. Relog or reboot to see full changes" --title "Set global background"
fi

exit
