#!/usr/bin/env bash

xbps-install -Syu amdvlk linux-firmware-amd mesa-vaapi mesa-vdpau mesa-vulkan-radeon vulkan-loader xf86-video-amdgpu xf86-video-ati
xbps-remove -Ry linux-firmware-intel linux-firmware-nvidia xf86-video-nouveau

echo ""
echo "Installation complete"
sleep 5
exit
