#!/usr/bin/env bash

_user="$(who|awk 'NR==1 {print $1}')"

xbps-install -Syu intel-media-driver intel-video-accel mesa-intel-dri mesa-vulkan-intel
xbps-remove -Ry linux-firmware-amd linux-firmware-nvidia

mkdir -pv /etc/X11/xorg.conf.d
cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
	Identifier "Intel Graphics"
	Driver "Intel"
	Option "AccelMethod" "sna"
	Option "TearFree" "True"
EndSection
EOF

echo ""
echo "Installation complete"
sleep 5
exit
